# Generated by Django 6.0.1 on 2026-09-10 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAppelLLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_length', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('cache_hit', 'Cache hit'), ('success', 'Success'), ('error', 'Error'), ('quota_cache', 'Quota cache'), ('quota_fallback', 'Quota fallback')], max_length=32)),
                ('cache_hit', models.BooleanField()),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_hash', 'created_at'], name='api_journal_user_ha_3edb9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntreeCacheRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=255, unique=True)),
                ('recommandation', models.JSONField()),
                ('expire_a', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_cache_recommandation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['utilisateur', 'expire_a'], name='api_entreec_utilisa_3b7358_idx')],
            },
        ),
    ]
