# Generated by Django 6.0.1 on 2026-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_llm_cache_and_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalappelllm',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='journalappelllm',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['cache_hit', 'success', 'error', 'quota_cache', 'quota_fallback'])), name='api_journal_status_valid'),
        ),
    ]
