# Generated by Django 6.0.1 on 2026-09-13 21:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journal_llm_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('titre', models.CharField(max_length=255)),
                ('entreprise', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_poste', models.CharField(choices=[('stage', 'Stage'), ('alternance', 'Alternance'), ('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('statut', models.CharField(choices=[('a_postuler', 'A postuler'), ('postule', 'Postule'), ('entretien', 'Entretien'), ('refuse', 'Refuse'), ('accepte', 'Accepte')], default='a_postuler', max_length=20)),
                ('source_extraction', models.CharField(blank=True, max_length=20)),
                ('source_canal', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('welcome_jungle', 'Welcome to the Jungle'), ('site_direct', "Site de l'entreprise"), ('cooptation', 'Cooptation / reseau'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('favori', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('cv_utilise', models.CharField(blank=True, max_length=255)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('date_relance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'url'), name='unique_url_par_utilisateur')],
            },
        ),
    ]
