# Generated by Django 6.0.1 on 2026-09-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidature'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalappelllm',
            name='usage',
            field=models.CharField(choices=[('recommandation', 'Recommandation'), ('candidature', 'Candidature')], default='recommandation', max_length=20),
        ),
    ]
