# Generated by Django 6.0.1 on 2026-09-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_journalappelllm_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='lieu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidature',
            name='mode_travail',
            field=models.CharField(blank=True, choices=[('sur_site', 'Sur site'), ('hybride', 'Hybride'), ('teletravail', 'Teletravail')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActionCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('envoyee', 'Candidature envoyee'), ('relance', 'Relance'), ('entretien_tel', 'Entretien telephonique'), ('entretien_visio', 'Entretien visio'), ('entretien_presentiel', 'Entretien presentiel'), ('test_technique', 'Test technique'), ('offre_recue', 'Offre recue'), ('reponse_negative', 'Reponse negative'), ('note', 'Note libre')], max_length=30)),
                ('date_action', models.DateTimeField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.candidature')),
            ],
            options={
                'ordering': ['-date_action', '-id'],
            },
        ),
    ]
