# Generated by Django 6.0.1 on 2026-09-22 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cvutilisateur_emailcandidature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionGmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_chiffre', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('connected', 'Connecte'), ('reconnect_required', 'Reconnexion requise')], default='connected', max_length=20)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connexion_gmail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentativeOAuthGmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_digest', models.CharField(max_length=64, unique=True)),
                ('pkce_verifier_chiffre', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_oauth_gmail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
