# Generated by Django 6.0.1 on 2026-09-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_connexiongmail_tentativeoauthgmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcandidature',
            name='manual_confirmation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcandidature',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='api.emailcandidature'),
        ),
        migrations.AddConstraint(
            model_name='emailcandidature',
            constraint=models.UniqueConstraint(condition=models.Q(('retry_of__isnull', False)), fields=('retry_of',), name='unique_email_retry_successor'),
        ),
    ]
