# Generated by Django 6.0.1 on 2026-02-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(default='#95a5a6', max_length=7)),
                ('emoji', models.CharField(default='📁', max_length=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_productive_debut', models.TimeField(default='09:00')),
                ('heure_productive_fin', models.TimeField(default='17:00')),
                ('theme', models.CharField(default='clair', max_length=20)),
                ('notifications_actives', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateTimeField()),
                ('priorite', models.IntegerField(choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute'), (4, 'Urgente')], default=2)),
                ('couleur', models.CharField(default='#3498db', max_length=7)),
                ('emoji', models.CharField(default='📝', max_length=10)),
                ('completee', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.categorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_echeance', '-priorite'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heure_completion', models.TimeField()),
                ('duree_estimee', models.IntegerField(help_text='Durée en minutes')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to=settings.AUTH_USER_MODEL)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.tache')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
