# Generated by Django 6.0.1 on 2026-09-10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='couleur',
            field=models.CharField(
                default='#3498db',
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        '^#[0-9A-Fa-f]{6}$',
                        'Utilisez une couleur au format #RRGGBB.',
                    )
                ],
            ),
        ),
    ]
